import type {
  ActivityItem,
  AuditLogItem,
  Company,
  CompanyDocument,
  Contact,
  TaskItem,
  TeamMember,
} from "./types";

/**
 * Seed data for the prototype. Realistic freight-brokerage entities (the
 * real CRM's actual domain — hotshot/equipment/general freight, per
 * src/lib/company.ts) with plausible names, never "Company 1" / "Test Doc".
 * Nothing here is real production data — every name, contact, and number is
 * invented for this prototype.
 */

const iso = (daysAgo: number, hour = 9) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};
const isoFuture = (daysAhead: number, hour = 9) => iso(-daysAhead, hour);

export const TEAM: TeamMember[] = [
  {
    id: "u-brent",
    name: "Brent Harbin",
    email: "brent@hellohotshot.com",
    title: "Founder / Broker",
    role: "owner",
    isPrimaryOwner: true,
    isActive: true,
    canViewAllCompanies: true,
    companiesOwned: 6,
    openTasks: 3,
    lastActiveAt: iso(0, 8),
    createdAt: iso(420),
  },
  {
    id: "u-marcus",
    name: "Marcus Reyes",
    email: "marcus@hellohotshot.com",
    title: "Sales Manager",
    role: "admin",
    isPrimaryOwner: false,
    isActive: true,
    canViewAllCompanies: true,
    companiesOwned: 5,
    openTasks: 4,
    lastActiveAt: iso(0, 10),
    createdAt: iso(310),
  },
  {
    id: "u-dana",
    name: "Dana Whitfield",
    email: "dana@hellohotshot.com",
    title: "Account Executive",
    role: "agent",
    isPrimaryOwner: false,
    isActive: true,
    canViewAllCompanies: false,
    companiesOwned: 5,
    openTasks: 6,
    lastActiveAt: iso(0, 11),
    createdAt: iso(260),
  },
  {
    id: "u-caleb",
    name: "Caleb Ortiz",
    email: "caleb@hellohotshot.com",
    title: "Account Executive",
    role: "agent",
    isPrimaryOwner: false,
    isActive: true,
    canViewAllCompanies: false,
    companiesOwned: 3,
    openTasks: 2,
    lastActiveAt: iso(1, 15),
    createdAt: iso(180),
  },
  {
    id: "u-priya",
    name: "Priya Nandan",
    email: "priya@hellohotshot.com",
    title: "Account Executive",
    role: "agent",
    isPrimaryOwner: false,
    isActive: false,
    canViewAllCompanies: false,
    companiesOwned: 0,
    openTasks: 0,
    lastActiveAt: iso(41, 9),
    createdAt: iso(140),
  },
];

export const COMPANIES: Company[] = [
  {
    id: "c-lonestar-steel",
    name: "Lone Star Steel Fabrication",
    industry: "Steel Fabrication",
    city: "Odessa",
    state: "TX",
    stage: "active_customer",
    assignedUserId: "u-marcus",
    phone: "(432) 555-0142",
    website: "lonestarsteelfab.com",
    fitRating: 5,
    tags: ["Flatbed", "Repeat shipper"],
    lastContactAt: iso(2),
    createdAt: iso(310),
    annualFreightSpend: "$1.2M+",
    primaryContactId: "ct-diane-holt",
    notes: "Long-standing account. Ships structural steel weekly to West Texas oilfield sites.",
  },
  {
    id: "c-permian-oilfield",
    name: "Permian Basin Oilfield Supply",
    industry: "Oilfield Equipment",
    city: "Midland",
    state: "TX",
    stage: "active_customer",
    assignedUserId: "u-brent",
    phone: "(432) 555-0188",
    website: "permianoilfieldsupply.com",
    fitRating: 5,
    tags: ["Hotshot", "Time-critical"],
    lastContactAt: iso(1),
    createdAt: iso(280),
    annualFreightSpend: "$860K",
    primaryContactId: "ct-roy-medina",
    notes: "High-frequency hotshot loads — wellhead parts, same-day turnarounds.",
  },
  {
    id: "c-crossroads-ag",
    name: "Crossroads Ag Equipment",
    industry: "Agricultural Equipment",
    city: "Lubbock",
    state: "TX",
    stage: "quoted",
    assignedUserId: "u-dana",
    phone: "(806) 555-0117",
    website: "crossroadsag.com",
    fitRating: 4,
    tags: ["Flatbed", "Seasonal"],
    lastContactAt: iso(4),
    createdAt: iso(64),
    annualFreightSpend: "$310K",
    primaryContactId: "ct-wanda-price",
    notes: "Quoted for planting-season equipment moves; awaiting PO.",
  },
  {
    id: "c-gulfcoast-modular",
    name: "Gulf Coast Modular Buildings",
    industry: "Modular Construction",
    city: "Beaumont",
    state: "TX",
    stage: "negotiating",
    assignedUserId: "u-caleb",
    phone: "(409) 555-0163",
    website: "gulfcoastmodular.com",
    fitRating: 4,
    tags: ["Oversize", "RGN"],
    lastContactAt: iso(0),
    createdAt: iso(51),
    annualFreightSpend: "$540K",
    primaryContactId: "ct-felix-tran",
    notes: "Negotiating a standing-lane rate for modular office units to Houston metro.",
  },
  {
    id: "c-panhandle-grain",
    name: "Panhandle Grain Cooperative",
    industry: "Agriculture",
    city: "Amarillo",
    state: "TX",
    stage: "qualified",
    assignedUserId: "u-dana",
    phone: "(806) 555-0129",
    website: "panhandlegrain.coop",
    fitRating: 3,
    tags: ["Van", "Bulk"],
    lastContactAt: iso(9),
    createdAt: iso(38),
    annualFreightSpend: "$180K",
    primaryContactId: "ct-oscar-lin",
    notes: "Discovery call done. Needs capacity for harvest-season grain hauls.",
  },
  {
    id: "c-desert-crane",
    name: "Desert Crane & Rigging",
    industry: "Heavy Equipment",
    city: "El Paso",
    state: "TX",
    stage: "active_customer",
    assignedUserId: "u-marcus",
    phone: "(915) 555-0155",
    website: "desertcranerigging.com",
    fitRating: 5,
    tags: ["Oversize", "Permit loads"],
    lastContactAt: iso(6),
    createdAt: iso(255),
    annualFreightSpend: "$920K",
    primaryContactId: "ct-monica-reeves",
    notes: "Crane component moves, heavy permitting. Dispatch prefers text confirmations.",
  },
  {
    id: "c-brazos-precast",
    name: "Brazos Valley Precast",
    industry: "Concrete Products",
    city: "Waco",
    state: "TX",
    stage: "contacted",
    assignedUserId: "u-caleb",
    phone: "(254) 555-0104",
    website: "brazosprecast.com",
    fitRating: 3,
    tags: ["Flatbed", "Heavy"],
    lastContactAt: iso(12),
    createdAt: iso(20),
    annualFreightSpend: "$95K",
    primaryContactId: "ct-hector-vega",
    notes: "Left voicemail with plant manager; following up Thursday.",
  },
  {
    id: "c-redriver-timber",
    name: "Red River Timber Co.",
    industry: "Lumber",
    city: "Texarkana",
    state: "TX",
    stage: "new_lead",
    assignedUserId: "u-dana",
    phone: "(903) 555-0171",
    website: "redrivertimber.com",
    fitRating: 2,
    tags: ["Flatbed"],
    lastContactAt: null,
    createdAt: iso(2),
    annualFreightSpend: "Unknown",
    primaryContactId: null,
    notes: "Inbound web inquiry — not yet worked.",
  },
  {
    id: "c-alamo-manufacturing",
    name: "Alamo Precision Manufacturing",
    industry: "Industrial Manufacturing",
    city: "San Antonio",
    state: "TX",
    stage: "won",
    assignedUserId: "u-marcus",
    phone: "(210) 555-0138",
    website: "alamoprecision.com",
    fitRating: 4,
    tags: ["Van", "LTL"],
    lastContactAt: iso(3),
    createdAt: iso(70),
    annualFreightSpend: "$410K",
    primaryContactId: "ct-grace-nolan",
    notes: "Signed. Onboarding shipping desk this week before first live load.",
  },
  {
    id: "c-piney-woods",
    name: "Piney Woods Pipe & Supply",
    industry: "Industrial Supply",
    city: "Lufkin",
    state: "TX",
    stage: "lost",
    assignedUserId: "u-caleb",
    phone: "(936) 555-0192",
    website: "pineywoodspipe.com",
    fitRating: 2,
    tags: ["Flatbed"],
    lastContactAt: iso(48),
    createdAt: iso(96),
    annualFreightSpend: "$60K",
    primaryContactId: "ct-tommy-shaw",
    notes: "Went with an incumbent carrier on price. Revisit in Q1.",
  },
  {
    id: "c-hillcountry-solar",
    name: "Hill Country Solar Structures",
    industry: "Renewable Energy",
    city: "Fredericksburg",
    state: "TX",
    stage: "active_customer",
    assignedUserId: "u-brent",
    phone: "(830) 555-0121",
    website: "hillcountrysolar.com",
    fitRating: 5,
    tags: ["Oversize", "Repeat shipper"],
    lastContactAt: iso(1),
    createdAt: iso(190),
    annualFreightSpend: "$680K",
    primaryContactId: "ct-elena-brooks",
    notes: "Utility-scale solar racking. Consistent weekly volume.",
  },
  {
    id: "c-coastal-refinery",
    name: "Coastal Bend Refinery Services",
    industry: "Oil & Gas Services",
    city: "Corpus Christi",
    state: "TX",
    stage: "negotiating",
    assignedUserId: "u-dana",
    phone: "(361) 555-0149",
    website: "coastalbendrs.com",
    fitRating: 4,
    tags: ["Hotshot", "Time-critical"],
    lastContactAt: iso(0),
    createdAt: iso(29),
    annualFreightSpend: "$260K",
    primaryContactId: "ct-neil-park",
    notes: "Turnaround-season hotshot support — rate sheet sent, awaiting sign-off.",
  },
  {
    id: "c-caprock-cotton",
    name: "Caprock Cotton Gin & Warehouse",
    industry: "Agriculture",
    city: "Plainview",
    state: "TX",
    stage: "qualified",
    assignedUserId: "u-caleb",
    phone: "(806) 555-0110",
    website: "caprockcotton.com",
    fitRating: 3,
    tags: ["Van", "Seasonal"],
    lastContactAt: iso(15),
    createdAt: iso(45),
    annualFreightSpend: "$140K",
    primaryContactId: "ct-sam-igbo",
    notes: "Gin manager wants ginning-season capacity locked in by August.",
  },
  {
    id: "c-blackland-dairy",
    name: "Blackland Dairy Equipment",
    industry: "Agricultural Equipment",
    city: "Waxahachie",
    state: "TX",
    stage: "new_lead",
    assignedUserId: "u-marcus",
    phone: "(972) 555-0166",
    website: "blacklanddairy.com",
    fitRating: 3,
    tags: ["Flatbed"],
    lastContactAt: null,
    createdAt: iso(1),
    annualFreightSpend: "Unknown",
    primaryContactId: null,
    notes: "Referral from Lone Star Steel. Not yet contacted.",
  },
];

export const CONTACTS: Contact[] = [
  { id: "ct-diane-holt", companyId: "c-lonestar-steel", name: "Diane Holt", title: "Logistics Manager", email: "diane.holt@lonestarsteelfab.com", phone: "(432) 555-0143", isDecisionMaker: true, lastContactedAt: iso(2), nextFollowupAt: isoFuture(3) },
  { id: "ct-ray-copeland", companyId: "c-lonestar-steel", name: "Ray Copeland", title: "Shipping Coordinator", email: "ray.copeland@lonestarsteelfab.com", phone: "(432) 555-0144", isDecisionMaker: false, lastContactedAt: iso(9), nextFollowupAt: null },
  { id: "ct-roy-medina", companyId: "c-permian-oilfield", name: "Roy Medina", title: "Operations Director", email: "roy.medina@permianoilfieldsupply.com", phone: "(432) 555-0189", isDecisionMaker: true, lastContactedAt: iso(1), nextFollowupAt: isoFuture(1) },
  { id: "ct-wanda-price", companyId: "c-crossroads-ag", name: "Wanda Price", title: "Owner", email: "wanda@crossroadsag.com", phone: "(806) 555-0118", isDecisionMaker: true, lastContactedAt: iso(4), nextFollowupAt: isoFuture(2) },
  { id: "ct-felix-tran", companyId: "c-gulfcoast-modular", name: "Felix Tran", title: "VP of Operations", email: "felix.tran@gulfcoastmodular.com", phone: "(409) 555-0164", isDecisionMaker: true, lastContactedAt: iso(0), nextFollowupAt: isoFuture(0) },
  { id: "ct-oscar-lin", companyId: "c-panhandle-grain", name: "Oscar Lin", title: "General Manager", email: "oscar.lin@panhandlegrain.coop", phone: "(806) 555-0130", isDecisionMaker: true, lastContactedAt: iso(9), nextFollowupAt: isoFuture(5) },
  { id: "ct-monica-reeves", companyId: "c-desert-crane", name: "Monica Reeves", title: "Dispatch Lead", email: "monica.reeves@desertcranerigging.com", phone: "(915) 555-0156", isDecisionMaker: false, lastContactedAt: iso(6), nextFollowupAt: isoFuture(4) },
  { id: "ct-hector-vega", companyId: "c-brazos-precast", name: "Hector Vega", title: "Plant Manager", email: "hector.vega@brazosprecast.com", phone: "(254) 555-0105", isDecisionMaker: true, lastContactedAt: iso(12), nextFollowupAt: isoFuture(1) },
  { id: "ct-grace-nolan", companyId: "c-alamo-manufacturing", name: "Grace Nolan", title: "Shipping Desk Lead", email: "grace.nolan@alamoprecision.com", phone: "(210) 555-0139", isDecisionMaker: true, lastContactedAt: iso(3), nextFollowupAt: isoFuture(2) },
  { id: "ct-tommy-shaw", companyId: "c-piney-woods", name: "Tommy Shaw", title: "Owner", email: "tommy@pineywoodspipe.com", phone: "(936) 555-0193", isDecisionMaker: true, lastContactedAt: iso(48), nextFollowupAt: null },
  { id: "ct-elena-brooks", companyId: "c-hillcountry-solar", name: "Elena Brooks", title: "Logistics Manager", email: "elena.brooks@hillcountrysolar.com", phone: "(830) 555-0122", isDecisionMaker: true, lastContactedAt: iso(1), nextFollowupAt: isoFuture(6) },
  { id: "ct-neil-park", companyId: "c-coastal-refinery", name: "Neil Park", title: "Turnaround Coordinator", email: "neil.park@coastalbendrs.com", phone: "(361) 555-0150", isDecisionMaker: true, lastContactedAt: iso(0), nextFollowupAt: isoFuture(2) },
  { id: "ct-sam-igbo", companyId: "c-caprock-cotton", name: "Sam Igbo", title: "Gin Manager", email: "sam.igbo@caprockcotton.com", phone: "(806) 555-0111", isDecisionMaker: true, lastContactedAt: iso(15), nextFollowupAt: isoFuture(3) },
  { id: "ct-linda-farris", companyId: "c-lonestar-steel", name: "Linda Farris", title: "Controller", email: "linda.farris@lonestarsteelfab.com", phone: "(432) 555-0145", isDecisionMaker: false, lastContactedAt: iso(30), nextFollowupAt: null },
  { id: "ct-abel-nguyen", companyId: "c-permian-oilfield", name: "Abel Nguyen", title: "Yard Foreman", email: "abel.nguyen@permianoilfieldsupply.com", phone: "(432) 555-0190", isDecisionMaker: false, lastContactedAt: iso(5), nextFollowupAt: null },
  { id: "ct-jackie-moss", companyId: "c-desert-crane", name: "Jackie Moss", title: "Owner", email: "jackie.moss@desertcranerigging.com", phone: "(915) 555-0157", isDecisionMaker: true, lastContactedAt: iso(20), nextFollowupAt: isoFuture(10) },
  { id: "ct-derek-holloway", companyId: null, name: "Derek Holloway", title: "Freight Broker (referral)", email: "derek@indfreightpartners.com", phone: "(469) 555-0107", isDecisionMaker: false, lastContactedAt: iso(25), nextFollowupAt: null },
  { id: "ct-may-sutton", companyId: "c-hillcountry-solar", name: "May Sutton", title: "Procurement", email: "may.sutton@hillcountrysolar.com", phone: "(830) 555-0123", isDecisionMaker: false, lastContactedAt: iso(11), nextFollowupAt: isoFuture(8) },
  { id: "ct-owen-castillo", companyId: "c-coastal-refinery", name: "Owen Castillo", title: "Site Superintendent", email: "owen.castillo@coastalbendrs.com", phone: "(361) 555-0151", isDecisionMaker: false, lastContactedAt: iso(7), nextFollowupAt: null },
  { id: "ct-bethany-cole", companyId: "c-alamo-manufacturing", name: "Bethany Cole", title: "AP Contact", email: "bethany.cole@alamoprecision.com", phone: "(210) 555-0140", isDecisionMaker: false, lastContactedAt: iso(3), nextFollowupAt: null },
];

export const TASKS: TaskItem[] = [
  { id: "t-1", title: "Call Diane re: next week's steel pickup", companyId: "c-lonestar-steel", contactId: "ct-diane-holt", assignedUserId: "u-marcus", dueAt: isoFuture(0), priority: "high", status: "open" },
  { id: "t-2", title: "Send updated rate sheet", companyId: "c-coastal-refinery", contactId: "ct-neil-park", assignedUserId: "u-dana", dueAt: isoFuture(0), priority: "high", status: "open" },
  { id: "t-3", title: "Follow up on Crossroads Ag quote", companyId: "c-crossroads-ag", contactId: "ct-wanda-price", assignedUserId: "u-dana", dueAt: isoFuture(2), priority: "normal", status: "open" },
  { id: "t-4", title: "First contact — Red River Timber inbound lead", companyId: "c-redriver-timber", contactId: null, assignedUserId: "u-dana", dueAt: isoFuture(1), priority: "normal", status: "open" },
  { id: "t-5", title: "Confirm modular lane rate w/ Felix", companyId: "c-gulfcoast-modular", contactId: "ct-felix-tran", assignedUserId: "u-caleb", dueAt: iso(-1), priority: "high", status: "open" },
  { id: "t-6", title: "Onboard Alamo shipping desk", companyId: "c-alamo-manufacturing", contactId: "ct-grace-nolan", assignedUserId: "u-marcus", dueAt: isoFuture(3), priority: "normal", status: "open" },
  { id: "t-7", title: "Revisit Piney Woods pipe in Q1", companyId: "c-piney-woods", contactId: "ct-tommy-shaw", assignedUserId: "u-caleb", dueAt: isoFuture(30), priority: "low", status: "open" },
  { id: "t-8", title: "Log this week's Desert Crane loads", companyId: "c-desert-crane", contactId: null, assignedUserId: "u-marcus", dueAt: iso(2), priority: "normal", status: "done" },
];

export const DOCUMENTS: CompanyDocument[] = [
  { id: "d-1", companyId: "c-lonestar-steel", type: "rate_confirmation", label: "Rate Confirmation — LSS-0842", createdAt: iso(2), createdByUserId: "u-marcus", status: "signed" },
  { id: "d-2", companyId: "c-lonestar-steel", type: "bill_of_lading", label: "Bill of Lading — LSS-0842", createdAt: iso(1), createdByUserId: "u-marcus", status: "signed" },
  { id: "d-3", companyId: "c-permian-oilfield", type: "rate_confirmation", label: "Rate Confirmation — PBO-1190", createdAt: iso(1), createdByUserId: "u-brent", status: "sent" },
  { id: "d-4", companyId: "c-desert-crane", type: "rate_confirmation", label: "Rate Confirmation — DCR-0311", createdAt: iso(6), createdByUserId: "u-marcus", status: "signed" },
  { id: "d-5", companyId: "c-desert-crane", type: "bill_of_lading", label: "Bill of Lading — DCR-0311", createdAt: iso(5), createdByUserId: "u-marcus", status: "signed" },
  { id: "d-6", companyId: "c-hillcountry-solar", type: "rate_confirmation", label: "Rate Confirmation — HCS-0705", createdAt: iso(1), createdByUserId: "u-brent", status: "draft" },
  { id: "d-7", companyId: "c-alamo-manufacturing", type: "rate_confirmation", label: "Rate Confirmation — APM-0022", createdAt: iso(3), createdByUserId: "u-marcus", status: "sent" },
];

export const ACTIVITIES: ActivityItem[] = [
  { id: "a-1", kind: "call", companyId: "c-lonestar-steel", contactId: "ct-diane-holt", authorId: "u-marcus", title: "Call · Confirmed", body: "Confirmed pickup window for next Tuesday's flatbed load.", occurredAt: iso(2) },
  { id: "a-2", kind: "stage_change", companyId: "c-gulfcoast-modular", contactId: null, authorId: "u-caleb", title: "Stage changed: Contacted → Negotiating", body: null, occurredAt: iso(0, 14) },
  { id: "a-3", kind: "email", companyId: "c-coastal-refinery", contactId: "ct-neil-park", authorId: "u-dana", title: "Email · Rate sheet sent", body: "Sent turnaround-season rate sheet for review.", occurredAt: iso(0, 10) },
  { id: "a-4", kind: "note", companyId: "c-permian-oilfield", contactId: "ct-roy-medina", authorId: "u-brent", title: "Note", body: "Roy mentioned Q3 volume will roughly double due to a new pad site coming online.", occurredAt: iso(1) },
  { id: "a-5", kind: "document", companyId: "c-lonestar-steel", contactId: null, authorId: "u-marcus", title: "Document generated: Bill of Lading", body: "LSS-0842", occurredAt: iso(1) },
  { id: "a-6", kind: "call", companyId: "c-crossroads-ag", contactId: "ct-wanda-price", authorId: "u-dana", title: "Call · Left voicemail", body: null, occurredAt: iso(4) },
  { id: "a-7", kind: "task", companyId: "c-alamo-manufacturing", contactId: "ct-grace-nolan", authorId: "u-marcus", title: "Task completed: Send onboarding packet", body: null, occurredAt: iso(3) },
  { id: "a-8", kind: "stage_change", companyId: "c-alamo-manufacturing", contactId: null, authorId: "u-marcus", title: "Stage changed: Negotiating → Won", body: null, occurredAt: iso(3, 16) },
  { id: "a-9", kind: "call", companyId: "c-desert-crane", contactId: "ct-monica-reeves", authorId: "u-marcus", title: "Call · Scheduled", body: "Scheduled two RGN loads for the crane boom sections.", occurredAt: iso(6) },
  { id: "a-10", kind: "note", companyId: "c-hillcountry-solar", contactId: "ct-elena-brooks", authorId: "u-brent", title: "Note", body: "Elena confirmed weekly volume through end of year — good renewal signal.", occurredAt: iso(1) },
  { id: "a-11", kind: "email", companyId: "c-panhandle-grain", contactId: "ct-oscar-lin", authorId: "u-dana", title: "Email · Intro sent", body: null, occurredAt: iso(9) },
  { id: "a-12", kind: "call", companyId: "c-brazos-precast", contactId: "ct-hector-vega", authorId: "u-caleb", title: "Call · No answer", body: "Left voicemail, will try again Thursday.", occurredAt: iso(12) },
  { id: "a-13", kind: "document", companyId: "c-permian-oilfield", contactId: null, authorId: "u-brent", title: "Document generated: Rate Confirmation", body: "PBO-1190", occurredAt: iso(1) },
  { id: "a-14", kind: "stage_change", companyId: "c-caprock-cotton", contactId: null, authorId: "u-caleb", title: "Stage changed: Contacted → Qualified", body: null, occurredAt: iso(15, 11) },
  { id: "a-15", kind: "call", companyId: "c-coastal-refinery", contactId: "ct-owen-castillo", authorId: "u-dana", title: "Call · Confirmed", body: "Walked through turnaround schedule for the next 6 weeks.", occurredAt: iso(7) },
];

export const AUDIT_LOG: AuditLogItem[] = [
  { id: "al-1", action: "user_suspended", actorId: "u-brent", targetUserId: "u-priya", targetCompanyId: null, summary: "Brent Harbin suspended Priya Nandan and reassigned her companies to Caleb Ortiz", detail: "3 companies reassigned before deactivation.", occurredAt: iso(41, 9) },
  { id: "al-2", action: "role_changed", actorId: "u-brent", targetUserId: "u-marcus", targetCompanyId: null, summary: "Brent Harbin promoted Marcus Reyes to Admin", detail: null, occurredAt: iso(180, 13) },
  { id: "al-3", action: "visibility_changed", actorId: "u-brent", targetUserId: "u-dana", targetCompanyId: null, summary: "Brent Harbin restricted Dana Whitfield to her own companies only", detail: "Can view all companies: On → Off", occurredAt: iso(90, 15) },
  { id: "al-4", action: "company_reassigned", actorId: "u-marcus", targetUserId: "u-caleb", targetCompanyId: "c-brazos-precast", summary: "Marcus Reyes reassigned Brazos Valley Precast to Caleb Ortiz", detail: null, occurredAt: iso(20, 9) },
  { id: "al-5", action: "user_invited", actorId: "u-brent", targetUserId: "u-caleb", targetCompanyId: null, summary: "Brent Harbin invited Caleb Ortiz as Sales Agent", detail: null, occurredAt: iso(180, 9) },
  { id: "al-6", action: "org_settings_changed", actorId: "u-brent", targetUserId: null, targetCompanyId: null, summary: "Brent Harbin updated the organization's brokerage letterhead info", detail: "MC number and remit-to address updated.", occurredAt: iso(60, 10) },
  { id: "al-7", action: "user_reactivated", actorId: "u-brent", targetUserId: "u-priya", targetCompanyId: null, summary: "Brent Harbin reactivated Priya Nandan (test — reverted same day)", detail: null, occurredAt: iso(41, 17) },
  { id: "al-8", action: "user_suspended", actorId: "u-brent", targetUserId: "u-priya", targetCompanyId: null, summary: "Brent Harbin suspended Priya Nandan", detail: "Final suspension after reactivation test.", occurredAt: iso(40, 9) },
  { id: "al-9", action: "role_changed", actorId: "u-brent", targetUserId: "u-dana", targetCompanyId: null, summary: "Brent Harbin confirmed Dana Whitfield as Sales Agent (no change)", detail: null, occurredAt: iso(260, 9) },
  { id: "al-10", action: "company_reassigned", actorId: "u-brent", targetUserId: "u-brent", targetCompanyId: "c-hillcountry-solar", summary: "Brent Harbin took ownership of Hill Country Solar Structures", detail: null, occurredAt: iso(190, 9) },
];
