/**
 * "Needs Attention" aggregate for the Today page (v2-design.md §3, house
 * rule: "the entire alert stack is generated by the notification model's
 * rules registry"). Phase 4e — READ-ONLY. This module answers "what costs
 * money if the owner misses it," across five signals, each reusing the
 * existing audited-correct V1 rule rather than re-deriving it:
 *
 *   - documents  — delivered loads missing rate con / BOL, or missing/zero
 *                  odometer (`incompleteGaps()`, lib/dispatch/alerts.ts).
 *   - receivables — delivered/TONU'd loads unpaid past the 40-day term
 *                  (`listCarrierReceivables()`, lib/data/receivables.ts —
 *                  itself built on the one `computeCarrierAR` rule).
 *   - expenses   — active recurring expenses missing amount/date/account/
 *                  category (`expenseGaps()`, lib/dispatch/alerts.ts).
 *   - maintenance — repair reminders overdue or due soon
 *                  (`getMaintenanceOverview()`, lib/data/maintenance.ts).
 *   - trips      — active trips with no end date yet, longest-open first.
 *
 * Scope note: this module talks to Supabase directly (isDemoMode()-branched)
 * rather than growing the shared `DataSource` interface, matching the
 * precedent `lib/data/receivables.ts`/`maintenance.ts`/
 * `recurring-expenses.ts` already set — multiple other /tms-v2 screens are
 * being built concurrently against the shared `lib/demo/*` files and
 * `nav.config` in this same phase; touching those here would risk stepping
 * on that work mid-flight. Where a read-only helper already exists
 * (`listCarrierReceivables`, `getMaintenanceOverview`, `listTrips`), it's
 * reused as-is instead of re-querying the same tables a second time.
 *
 * Dismiss/undo (Phase 5D): reuses V1's own `dismissed_alerts` table and
 * src/app/admin/(authed)/alert-actions.ts's dismissAlert/restoreAlert
 * unchanged (upsert/delete keyed by alert_key = this module's own
 * AttentionItem.id, so no format translation needed) via a thin tms-v2
 * wrapper — see src/actions/tms-v2/attention.ts. The read side here is
 * tolerant of the table not existing yet (same as V1's own dashboard read),
 * so a not-yet-applied migration degrades to "nothing dismissed" instead of
 * a broken page.
 */

import { isDemoMode } from "@/lib/admin/demo";
import { createServiceRoleClient } from "@/lib/supabase/server";
import { buildDemoData, DEMO_BROKERS } from "@/lib/demo/demo-dataset";
import {
  incompleteGaps,
  expenseGaps,
  GAP_LABEL,
  EXPENSE_GAP_LABEL,
} from "@/lib/dispatch/alerts";
import { formatMoney } from "@/lib/domain/money";
import { parseServerTimestamp } from "@/lib/domain/dates";
import { listCarrierReceivables, RECEIVABLE_OVERDUE_DAYS } from "./receivables";
import { getMaintenanceOverview } from "./maintenance";
import { listTrips } from "./trips";
import { listActiveLoads } from "./loads";

export type AttentionCategory = "documents" | "receivables" | "expenses" | "maintenance" | "trips" | "applications" | "quotes" | "opportunity";
/** "info" is a calm, non-urgent nudge (e.g. the empty-truck opportunity
 * card) — never counted in the red/amber badges, so it can't read as an
 * alert. */
export type AttentionSeverity = "red" | "amber" | "info";

export type AttentionItem = {
  id: string;
  category: AttentionCategory;
  severity: AttentionSeverity;
  /** The thing itself — load/broker, reminder name, trip name. */
  title: string;
  /** Why it matters, in one line — the gap, the age, the amount. */
  reason: string;
  href: string;
};

export type NeedsAttention = {
  items: AttentionItem[];
  redCount: number;
  amberCount: number;
};

function num(v: number | string | null | undefined): number {
  if (v == null) return 0;
  const n = typeof v === "number" ? v : Number(v);
  return Number.isFinite(n) ? n : 0;
}

// A one-truck operation's realistic ceiling for a single bounded scan —
// same reasoning as receivables.ts's AR_AGGREGATE_CAP: generous enough that
// in practice nothing is missed, while keeping the query bounded rather
// than a true unbounded full-table read (the pattern the audit flagged
// repeatedly in /admin, v2-design.md's non-negotiable #4).
const LOADS_SCAN_CAP = 300;

// ---------------------------------------------------------------------------
// Documents — delivered loads missing rate con / BOL / odometer.
// ---------------------------------------------------------------------------

type DocGapRaw = {
  id: string;
  loadNumber: string | null;
  brokerName: string | null;
  origin: string | null;
  destination: string | null;
  odoAssigned: number | null;
  odoLoaded: number | null;
  odoDelivered: number | null;
  hasRateCon: boolean;
  hasBol: boolean;
};

async function fetchDocGapRaw(): Promise<DocGapRaw[]> {
  if (await isDemoMode()) {
    const { loads } = buildDemoData();
    const brokerNameById = new Map(DEMO_BROKERS.map((b) => [b.id, b.name]));
    // The demo dataset ships no fake documents at all (same convention
    // getLoadDetail()'s demo branch uses), so every delivered demo load
    // reads as missing both rate con and BOL — a real, if simplified,
    // showcase of the signal rather than a fabricated one.
    return loads
      .filter((l) => l.status === "delivered")
      .map((l) => ({
        id: l.id,
        loadNumber: l.loadNumber,
        brokerName: brokerNameById.get(l.brokerId) ?? null,
        origin: l.origin,
        destination: l.destination,
        odoAssigned: l.odoAssigned,
        odoLoaded: l.odoLoaded,
        odoDelivered: l.odoDelivered,
        hasRateCon: false,
        hasBol: false,
      }));
  }

  const sb = createServiceRoleClient();
  const { data: loadRows } = await sb
    .from("loads")
    .select("id, load_number, broker_name, origin, destination, delivery_date, odo_assigned, odo_loaded, odo_delivered")
    .eq("status", "delivered")
    .is("deleted_at", null)
    .order("delivery_date", { ascending: false })
    .limit(LOADS_SCAN_CAP)
    .returns<
      {
        id: string;
        load_number: string | null;
        broker_name: string | null;
        origin: string | null;
        destination: string | null;
        delivery_date: string | null;
        odo_assigned: number | null;
        odo_loaded: number | null;
        odo_delivered: number | null;
      }[]
    >();
  const loads = loadRows ?? [];
  const ids = loads.map((l) => l.id);

  const docCounts = new Map<string, { rate_con: number; bol: number }>();
  if (ids.length > 0) {
    const { data: docRows } = await sb
      .from("load_documents")
      .select("load_id, kind")
      .in("load_id", ids)
      .in("kind", ["rate_con", "bol"])
      .returns<{ load_id: string; kind: string }[]>();
    for (const d of docRows ?? []) {
      const c = docCounts.get(d.load_id) ?? { rate_con: 0, bol: 0 };
      if (d.kind === "rate_con") c.rate_con += 1;
      if (d.kind === "bol") c.bol += 1;
      docCounts.set(d.load_id, c);
    }
  }

  return loads.map((l) => {
    const c = docCounts.get(l.id) ?? { rate_con: 0, bol: 0 };
    return {
      id: l.id,
      loadNumber: l.load_number,
      brokerName: l.broker_name,
      origin: l.origin,
      destination: l.destination,
      odoAssigned: l.odo_assigned,
      odoLoaded: l.odo_loaded,
      odoDelivered: l.odo_delivered,
      hasRateCon: c.rate_con > 0,
      hasBol: c.bol > 0,
    };
  });
}

async function getDocumentGapItems(): Promise<AttentionItem[]> {
  const raw = await fetchDocGapRaw();
  return raw
    .map((l) => ({
      l,
      gaps: incompleteGaps({
        hasRateCon: l.hasRateCon,
        hasBol: l.hasBol,
        odoAssigned: l.odoAssigned,
        odoLoaded: l.odoLoaded,
        odoDelivered: l.odoDelivered,
      }),
    }))
    .filter((r) => r.gaps.length > 0)
    .map(({ l, gaps }) => ({
      id: `documents:${l.id}`,
      category: "documents" as const,
      severity: "amber" as const,
      title: `${l.brokerName?.trim() || "No broker"} — #${l.loadNumber?.trim() || l.id.slice(0, 8)}`,
      reason: `${gaps.map((g) => GAP_LABEL[g]).join(", ")} · ${l.origin ?? "—"} → ${l.destination ?? "—"}`,
      // Land pre-scrolled on the section that fixes the gap — odometer
      // first (it's the input a driver has in hand), documents otherwise.
      href: `/tms-v2/loads/${l.id}#${gaps.includes("odometer") ? "odometer" : "documents"}`,
    }));
}

// ---------------------------------------------------------------------------
// Receivables — delivered/TONU'd loads unpaid past the 40-day term, oldest
// first. Reuses listCarrierReceivables() as-is (v2-architecture.md §3a: the
// one carrier-A/R rule) rather than re-scanning `loads` a second time.
// ---------------------------------------------------------------------------

async function getReceivableItems(): Promise<AttentionItem[]> {
  const { rows } = await listCarrierReceivables({ pageSize: 200 });
  return rows
    .filter((r) => r.overdue)
    .map((r) => ({
      id: `receivable:${r.loadId}`,
      category: "receivables" as const,
      severity: "red" as const,
      title: `${r.brokerName?.trim() || "No broker"} — #${r.loadNumber?.trim() || r.loadId.slice(0, 8)}`,
      reason: `${r.daysOutstanding}d unpaid, past the ${RECEIVABLE_OVERDUE_DAYS}-day term · ${formatMoney(r.amount)} owed`,
      href: `/tms-v2/loads/${r.loadId}`,
    }));
}

// ---------------------------------------------------------------------------
// Expenses — active recurring expenses missing enough to know what they are
// or when they charge (expenseGaps(), lib/dispatch/alerts.ts).
// ---------------------------------------------------------------------------

// Self-contained demo fixture, unrelated to recurring-expenses.ts's own demo
// rows (same "stays local rather than growing a shared file mid-phase"
// precedent that module documents) — one incomplete expense so the signal
// has something real to show in demo mode.
function demoExpenseGapItems(): AttentionItem[] {
  return [
    {
      id: "expense:demo-exp-incomplete",
      category: "expenses",
      severity: "amber",
      title: "New subscription (Demo)",
      reason: "No amount, No date, No account, No category",
      href: "/tms-v2/expenses",
    },
  ];
}

async function getExpenseGapItems(): Promise<AttentionItem[]> {
  if (await isDemoMode()) return demoExpenseGapItems();

  const sb = createServiceRoleClient();
  const [{ data: expenseRows }, { data: accountRows }] = await Promise.all([
    sb
      .from("recurring_expenses")
      .select("id, name, vendor, category, amount, frequency, day_of_month, day_of_week, start_date, card")
      .is("deleted_at", null)
      .eq("archived", false)
      .limit(1000)
      .returns<
        {
          id: string;
          name: string;
          vendor: string | null;
          category: string | null;
          amount: number | string | null;
          frequency: string | null;
          day_of_month: number | null;
          day_of_week: string | null;
          start_date: string | null;
          card: string | null;
        }[]
      >(),
    sb.from("expense_accounts").select("name").is("deleted_at", null).returns<{ name: string }[]>(),
  ]);

  const accountNames = new Set((accountRows ?? []).map((a) => a.name));

  return (expenseRows ?? [])
    .map((e) => ({
      e,
      gaps: expenseGaps(
        {
          amount: e.amount == null ? null : num(e.amount),
          frequency: e.frequency ?? "monthly",
          dayOfMonth: e.day_of_month,
          dayOfWeek: e.day_of_week,
          startDate: e.start_date,
          card: e.card,
          category: e.category,
        },
        accountNames,
      ),
    }))
    .filter((r) => r.gaps.length > 0)
    .map(({ e, gaps }) => ({
      id: `expense:${e.id}`,
      category: "expenses" as const,
      severity: "amber" as const,
      title: e.name?.trim() || e.vendor?.trim() || "Unnamed expense",
      reason: gaps.map((g) => EXPENSE_GAP_LABEL[g]).join(", "),
      href: "/tms-v2/expenses",
    }));
}

// ---------------------------------------------------------------------------
// Maintenance — reminders overdue or due soon. Reuses getMaintenanceOverview()
// as-is (freshness/status math lives in lib/dispatch/{repair-log,
// maintenance}.ts, the audited-correct V1 source).
// ---------------------------------------------------------------------------

async function getMaintenanceItems(): Promise<AttentionItem[]> {
  const overview = await getMaintenanceOverview();
  return overview.reminders
    .filter((r) => r.status === "overdue" || r.status === "soon")
    .map((r) => {
      const overdue = r.status === "overdue";
      const mi = r.milesRemaining;
      const reason =
        mi == null
          ? overdue
            ? "Overdue"
            : "Due soon"
          : mi <= 0
            ? `${Math.abs(mi).toLocaleString()} mi overdue`
            : `${mi.toLocaleString()} mi remaining — due soon`;
      return {
        id: `maintenance:${r.id}`,
        category: "maintenance" as const,
        severity: overdue ? ("red" as const) : ("amber" as const),
        title: r.label,
        reason,
        href: "/tms-v2/maintenance",
      };
    });
}

// ---------------------------------------------------------------------------
// Trips — active trips with no end date, longest-open first. Past
// TRIP_STALE_DAYS open, the gap escalates to red: an unclosed trip's
// PC-mile/expense figures stay incomplete (v2-design.md §7's "≈ incomplete"
// flag) until it's closed out, and a trip left open for two weeks is very
// likely just forgotten rather than genuinely still in progress.
// ---------------------------------------------------------------------------

const TRIP_STALE_DAYS = 14;

function daysSinceStart(iso: string | null, now: Date): number | null {
  const d = parseServerTimestamp(iso);
  if (!d) return null;
  const today = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  const started = Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate());
  const days = Math.floor((today - started) / 86_400_000);
  return days >= 0 ? days : 0;
}

async function getOngoingTripItems(): Promise<AttentionItem[]> {
  const { rows } = await listTrips({ status: "active", pageSize: 50 });
  const now = new Date();
  return rows
    .filter((t) => !t.endedAt)
    .map((t) => ({ t, days: daysSinceStart(t.startedAt, now) }))
    .sort((a, b) => (b.days ?? -1) - (a.days ?? -1))
    .map(({ t, days }) => {
      const stale = days != null && days >= TRIP_STALE_DAYS;
      return {
        id: `trip:${t.id}`,
        category: "trips" as const,
        severity: stale ? ("red" as const) : ("amber" as const),
        title: t.name?.trim() || `Trip ${t.id.slice(0, 8)}`,
        reason:
          days == null
            ? "Ongoing, no end date set"
            : `Open ${days}d, no end date — PC-mile and net figures stay incomplete until closed out`,
        href: `/tms-v2/trips/${t.id}`,
      };
    });
}

// ---------------------------------------------------------------------------
// New applications / new quote requests — the two "opportunity inbox"
// signals legacy's dashboard leads with (admin/(authed)/page.tsx's
// buildAlertGroups), ported here so tms-v2's Needs Attention mirrors the
// same alert set. "New" definitions match legacy exactly: an application
// is new if active and received in the last 24h (the table has no
// reviewed/handled field to key off); a quote request is new if active and
// still at its default lead_status = 'new'.
// ---------------------------------------------------------------------------

const NEW_APPLICATION_WINDOW_MS = 24 * 60 * 60 * 1000;

async function getNewApplicationItems(): Promise<AttentionItem[]> {
  if (await isDemoMode()) return [];

  const sb = createServiceRoleClient();
  const cutoff = new Date(Date.now() - NEW_APPLICATION_WINDOW_MS).toISOString();
  const { data } = await sb
    .from("applications")
    .select("id, name, created_at")
    .is("deleted_at", null)
    .gte("created_at", cutoff)
    .order("created_at", { ascending: false })
    .returns<{ id: string; name: string | null; created_at: string }[]>();

  return (data ?? []).map((a) => ({
    id: `applications:${a.id}`,
    category: "applications" as const,
    severity: "amber" as const,
    title: a.name?.trim() || "New applicant",
    reason: "Job application · last 24 hours",
    href: `/tms-v2/operations/applications/${a.id}`,
  }));
}

async function getNewQuoteItems(): Promise<AttentionItem[]> {
  if (await isDemoMode()) return [];

  const sb = createServiceRoleClient();
  const { data } = await sb
    .from("quote_requests")
    .select("id, name, created_at")
    .is("deleted_at", null)
    .eq("lead_status", "new")
    .order("created_at", { ascending: false })
    .returns<{ id: string; name: string | null; created_at: string }[]>();

  return (data ?? []).map((q) => ({
    id: `quotes:${q.id}`,
    category: "quotes" as const,
    severity: "amber" as const,
    title: q.name?.trim() || "New quote request",
    reason: "Not yet contacted",
    href: `/tms-v2/operations/${q.id}`,
  }));
}

// ---------------------------------------------------------------------------
// Opportunity — an empty truck is idle time worth turning into pipeline.
// Not a problem (no red/amber), so it's severity "info" and sorts last;
// "Keep Today calm, no cry-wolf" per the phase brief. Ties into Reach
// (Phase 5B) rather than a generic empty state.
// ---------------------------------------------------------------------------

async function getOpportunityItems(): Promise<AttentionItem[]> {
  const active = await listActiveLoads(1);
  if (active.length > 0) return [];
  return [
    {
      id: "opportunity:empty-truck",
      category: "opportunity" as const,
      severity: "info" as const,
      title: "Truck's empty",
      reason: "No active loads — farm a broker or send backhaul outreach",
      href: "/tms-v2/reach",
    },
  ];
}

// ---------------------------------------------------------------------------
// Dismissed alerts — reuses V1's own `dismissed_alerts` table as-is (see
// this module's header). Tolerant of the table not existing yet: a failed
// select just means "nothing dismissed", matching V1's own dashboard read.
// ---------------------------------------------------------------------------

async function fetchDismissedKeys(): Promise<Set<string>> {
  if (await isDemoMode()) return new Set();
  try {
    const sb = createServiceRoleClient();
    const { data, error } = await sb.from("dismissed_alerts").select("alert_key").returns<{ alert_key: string }[]>();
    if (error || !data) return new Set();
    return new Set(data.map((r) => r.alert_key));
  } catch {
    return new Set();
  }
}

// ---------------------------------------------------------------------------
// Aggregate — flat, prioritized list: red (overdue) before amber (soon)
// before info (opportunity), then a fixed category priority for
// readability within the same severity.
// ---------------------------------------------------------------------------

const CATEGORY_PRIORITY: Record<AttentionCategory, number> = {
  maintenance: 0,
  receivables: 1,
  documents: 2,
  trips: 3,
  expenses: 4,
  applications: 5,
  quotes: 6,
  opportunity: 7,
};

const SEVERITY_RANK: Record<AttentionSeverity, number> = { red: 0, amber: 1, info: 2 };

function sortItems(items: AttentionItem[]): AttentionItem[] {
  return items.slice().sort((a, b) => {
    if (a.severity !== b.severity) return SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity];
    return CATEGORY_PRIORITY[a.category] - CATEGORY_PRIORITY[b.category];
  });
}

export async function getNeedsAttention(): Promise<NeedsAttention> {
  const [documents, receivables, expenses, maintenance, trips, applications, quotes, opportunity, dismissed] = await Promise.all([
    getDocumentGapItems(),
    getReceivableItems(),
    getExpenseGapItems(),
    getMaintenanceItems(),
    getOngoingTripItems(),
    getNewApplicationItems(),
    getNewQuoteItems(),
    getOpportunityItems(),
    fetchDismissedKeys(),
  ]);
  const all = [...documents, ...receivables, ...expenses, ...maintenance, ...trips, ...applications, ...quotes, ...opportunity];
  const items = sortItems(all.filter((i) => !dismissed.has(i.id)));
  const redCount = items.filter((i) => i.severity === "red").length;
  const amberCount = items.filter((i) => i.severity === "amber").length;
  return { items, redCount, amberCount };
}
