-- 20260548000000_document_thumbnails.sql
-- Upload-time WebP thumbnails for uploaded photos (free-plan image shrinking;
-- Supabase Image Transformations aren't available on the Free plan). Each
-- image row stores the storage path of a ~256px WebP thumbnail generated by
-- sharp in the upload action; the grid <img> uses it, tap-to-view uses the
-- original. PDFs / HEIC get no thumbnail (thumb_path stays null).
--
-- The columns are already applied on the live DB; this file is a repo record.
-- IF NOT EXISTS makes it a no-op against the live schema.

alter table public.load_documents
  add column if not exists thumb_path text;

alter table public.maintenance_attachments
  add column if not exists thumb_path text;
