import { Card, CardHead } from "../../_shell/ui";
import { IconAiAgent } from "../../_shell/icons";
import { formatDateTime } from "../../_shell/format";
import type { CrmNote } from "./NotesSection";

/**
 * The company profile's "AI Research" tab — every is_ai=true crm_notes row
 * for this account, read-only. AI briefs are inserted externally (the AI
 * agent/review pipeline); there's nothing to compose or edit here, so this
 * stays a plain server-rendered panel (no client state needed) handed to
 * ProfileTabs as a ReactNode, same as the other tab panels. Styled distinctly
 * from Team Notes — amber accent, "AI Research" badge, "verify before
 * acting" framing — so a machine-written brief never reads as a teammate's
 * note.
 */
export function AiResearchSection({ notes }: { notes: CrmNote[] }) {
  return (
    <Card>
      <CardHead
        title="AI Research"
        hint="Generated by AI — verify before acting on it"
        right={
          <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-warn-bg text-warn">
            <IconAiAgent width={17} height={17} />
          </span>
        }
      />

      {notes.length === 0 ? (
        <p className="px-5 py-10 text-center text-[13.5px] text-fg-muted">
          No AI research yet. Briefs generated by the AI agent will show up here.
        </p>
      ) : (
        <ul className="divide-y divide-line-strong">
          {notes.map((n) => (
            <li key={n.id} className="border-l-4 border-l-warn bg-warn-bg/40 px-5 py-4">
              <div className="mb-1.5 flex items-center gap-2 text-[12px] text-fg-subtle">
                <span className="inline-flex items-center gap-1 rounded-full bg-warn-bg px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-warn">
                  <IconAiAgent width={11} height={11} />
                  AI Research
                </span>
                <span>·</span>
                <span>{formatDateTime(n.created_at)}</span>
              </div>
              <p className="whitespace-pre-wrap text-[13.5px] leading-relaxed text-fg">
                {n.body}
              </p>
            </li>
          ))}
        </ul>
      )}
    </Card>
  );
}
