"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { BTN_PRIMARY, Card, CardHead } from "../../_shell/ui";
import { IconAiAgent } from "../../_shell/icons";
import { formatDateTime } from "../../_shell/format";
import { requestAiResearch } from "./ai-research-actions";

export type CrmNote = {
  id: string;
  body: string;
  is_pinned: boolean;
  is_ai: boolean;
  created_at: string;
  author: string | null;
  contactName?: string | null;
};

/**
 * Best-effort split of a research note's free-text body into Summary / Key
 * findings / Sources. There's no structured storage for this yet (crm_notes
 * is a single `body` text column — see the module docstring below for what
 * DDL would change that) — this is a heuristic parse of plain text: a line
 * that's just a URL becomes a source, a line starting with a bullet marker
 * becomes a finding, everything else is summary. A body that doesn't follow
 * that shape just renders entirely as Summary — never a broken layout.
 */
function parseResearch(body: string): { summary: string; findings: string[]; sources: string[] } {
  const urlLine = /^https?:\/\/\S+$/;
  const bulletLine = /^[-•*]\s+(.*)$/;
  const findings: string[] = [];
  const sources: string[] = [];
  const summaryLines: string[] = [];

  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (urlLine.test(line)) {
      sources.push(line);
      continue;
    }
    const bullet = bulletLine.exec(line);
    if (bullet) {
      const urlInBullet = bullet[1].match(/https?:\/\/\S+/);
      if (urlInBullet && bullet[1].trim() === urlInBullet[0]) {
        sources.push(urlInBullet[0]);
      } else {
        findings.push(bullet[1]);
      }
      continue;
    }
    summaryLines.push(line);
  }

  return { summary: summaryLines.join(" "), findings, sources };
}

/**
 * The company profile's "AI Research" tab — every is_ai=true crm_notes row
 * for this account, each split into Summary/Key findings/Sources (see
 * parseResearch above). "Run research" doesn't call an AI provider itself —
 * see ai-research-actions.ts::requestAiResearch for exactly what it does and
 * why that's the honest boundary of what's reusable here without a new
 * integration. Styled distinctly from Team Notes — amber accent, "AI
 * Research" badge, "verify before acting" framing — so a machine-written
 * brief never reads as a teammate's note. Results still route through the
 * AI Review queue (ai_status pending_review → released) before anything
 * lands here, same as every other AI-sourced write in the CRM.
 *
 * DDL that WOULD upgrade this from a heuristic text parse to real structured
 * storage (not applied — reported per the "no schema without asking" rule):
 *   alter table public.crm_notes add column if not exists ai_summary text;
 *   alter table public.crm_notes add column if not exists ai_findings jsonb;
 *   alter table public.crm_notes add column if not exists ai_sources jsonb;
 */
export function AiResearchSection({
  accountId,
  notes,
  lastRequestedAt,
}: {
  accountId: string;
  notes: CrmNote[];
  lastRequestedAt: string | null;
}) {
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();

  function runResearch() {
    setError(null);
    startTransition(async () => {
      const res = await requestAiResearch(accountId);
      if (res.ok) router.refresh();
      else setError(res.error);
    });
  }

  return (
    <Card>
      <CardHead
        title="AI Research"
        hint={
          lastRequestedAt
            ? `Last requested ${formatDateTime(lastRequestedAt)}`
            : "Generated by AI — verify before acting on it"
        }
        right={
          <button
            type="button"
            onClick={runResearch}
            disabled={pending}
            className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[12.5px] font-semibold transition-colors ${BTN_PRIMARY}`}
          >
            <IconAiAgent width={14} height={14} />
            {pending ? "Requesting…" : "Run research"}
          </button>
        }
      />

      {error && <p className="px-5 pt-3 text-[12.5px] text-bad">{error}</p>}

      {notes.length === 0 ? (
        <p className="px-5 py-10 text-center text-[13.5px] text-fg-muted">
          No AI research yet. Run research above, or wait for a brief to land here.
        </p>
      ) : (
        <ul className="divide-y divide-line-strong">
          {notes.map((n) => {
            const { summary, findings, sources } = parseResearch(n.body);
            return (
              <li key={n.id} className="border-l-4 border-l-warn bg-warn-bg/40 px-5 py-4">
                <div className="mb-2 flex items-center gap-2 text-[12px] text-fg-subtle">
                  <span className="inline-flex items-center gap-1 rounded-full bg-warn-bg px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-warn">
                    <IconAiAgent width={11} height={11} />
                    AI Research
                  </span>
                  <span>·</span>
                  <span>{formatDateTime(n.created_at)}</span>
                </div>

                {summary && (
                  <p className="whitespace-pre-wrap text-[13.5px] leading-relaxed text-fg">
                    {summary}
                  </p>
                )}

                {findings.length > 0 && (
                  <div className="mt-3">
                    <p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-fg-subtle">
                      Key findings
                    </p>
                    <ul className="mt-1.5 flex flex-col gap-1">
                      {findings.map((f, i) => (
                        <li key={i} className="flex gap-2 text-[13px] leading-relaxed text-fg">
                          <span aria-hidden className="text-warn">
                            •
                          </span>
                          <span>{f}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {sources.length > 0 && (
                  <div className="mt-3">
                    <p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-fg-subtle">
                      Sources
                    </p>
                    <ul className="mt-1.5 flex flex-col gap-1">
                      {sources.map((url, i) => (
                        <li key={i}>
                          <a
                            href={url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="break-all text-[12.5px] text-accent hover:underline"
                          >
                            {url}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      )}
    </Card>
  );
}
